# Generated by Django 2.2.1 on 2019-05-15 15:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='default.png', upload_to='teacher_profile_pics')),
                ('expertise', models.CharField(choices=[('Computer Science', 'Computer Science'), ('Artificial Intelligence', 'Artificial Intelligence'), ('Web Development', 'Web Development'), ('Web Designing', 'Web Designing'), ('Internert Of Things', 'Internert Of Things')], default='Your expertise', max_length=224)),
                ('college', models.CharField(choices=[('Adi Sankara Institute Of Engineering And Technology', 'Adi Sankara Institute Of Engineering And Technology'), ('Federal Institute of Science And Technology', 'Federal Institute of Science And Technology'), ('Union Christian College', 'Union Christian College'), ('Indian Institute Of Technology', 'Indian Institute Of Technology'), ('Rajagiri College of Management & Applied Sciences', 'Rajagiri College of Management & Applied Sciences')], default='Your college', max_length=556)),
                ('video', models.FileField(null=True, upload_to='teacher_video')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='default.png', upload_to='student_profile_pics')),
                ('college', models.CharField(choices=[('Adi Sankara Institute Of Engineering And Technology', 'Adi Sankara Institute Of Engineering And Technology'), ('Federal Institute of Science And Technology', 'Federal Institute of Science And Technology'), ('Union Christian College', 'Union Christian College'), ('Indian Institute Of Technology', 'Indian Institute Of Technology'), ('Rajagiri College of Management & Applied Sciences', 'Rajagiri College of Management & Applied Sciences')], default='Your college', max_length=556)),
                ('number', models.CharField(default='91', max_length=14)),
                ('home', models.TextField(default='your home address')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InstitutionProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='default.png', upload_to='institution_profile_pics')),
                ('college', models.CharField(choices=[('Adi Sankara Institute Of Engineering And Technology', 'Adi Sankara Institute Of Engineering And Technology'), ('Federal Institute of Science And Technology', 'Federal Institute of Science And Technology'), ('Union Christian College', 'Union Christian College'), ('Indian Institute Of Technology', 'Indian Institute Of Technology'), ('Rajagiri College of Management & Applied Sciences', 'Rajagiri College of Management & Applied Sciences')], default='Your college', max_length=556)),
                ('video', models.FileField(null=True, upload_to='institution_video')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
